[project]
name = "tried-ce-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apache-airflow>=3.1.6",
    "fastapi>=0.117.1",
    "mlflow>=3.8.1",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
]
